export { default as Jumbotron } from './jumbotron'
export { default as About } from './about'
export { default as Section } from './section'
export { default as Projects } from './projects'
export { default as Courseworks } from './courseworks'