import Head from 'next/head'
import styles from '@styles/home.module.sass'
import { Jumbotron, About, Projects } from '@src/components/home'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Jumbotron/>
        <About/>
        <Projects showing={3}/>
      </div>

    </div>
  )
}
